### ISSUE TITLE
Energy consumption comparison Missing

### ISSUE THREAD

**Issue by DJ3vil** [ioBroker/ioBroker.vis-2-widgets-energy#114]
Energy consumption comparison is Missing for me.
![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-energy/assets/22053738/3ea3ff73-bd4e-4162-8ecc-8b92ee7e3f92)

**Comment by hombach** [comment]
I had the same issue - now fixed with 0.3.1

**Comment by GermanBluefox** [comment]
@DJ3vil does it fixed by you too?

**Comment by DJ3vil** [comment]
yep is working fine now, thanks!
