### ISSUE TITLE
Energy consumption comparison widget defective / not existent in V0.3.10

### ISSUE THREAD

**Issue by hombach** [ioBroker/ioBroker.vis-2-widgets-energy#195]
Existing instance of widget not working anymore. Widget disapeared in Editor.

downgrade to 0.3.9 fixes the issue

![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-energy/assets/63002482/0d263a2e-4bec-42f5-a084-7a46ab69e0c6)

![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-energy/assets/63002482/650e3bc0-c4d4-4b7e-b961-17d5704c8d8c)

**Comment by Feuer-sturm** [comment]
This is how it looks like with v0.3.9
![grafik](https://github.com/ioBroker/ioBroker.vis-2-widgets-energy/assets/25422320/678d6a2b-d7d8-4310-801d-4144c4269d80)

**Comment by Alex0176** [comment]
The same here - but if you uninstall and install the 0.3.10 the adapter does not exist anymore in VIS-2. You can only install the old version 0.3.9 and this works again.

**Comment by hombach** [comment]
I didn't uninstall - direkt downgrade to 0.3.9 from Admin GUI.

**Comment by hombach** [comment]
with 0.3.11 this issue is fixed - also as upgrade from 0.3.10

**Comment by GermanBluefox** [comment]
Fixed
