### ISSUE TITLE
V0.1.10 Bug mit Verbrauchsvergleich

### ISSUE THREAD

**Issue by Gurke258** [ioBroker/ioBroker.vis-2-widgets-energy#72]
Wenn ich das Widget Verbrauchsvergleich in mein View ziehe wird mein ganze ViS schwarz und ich muss sie komplett neu laden. Dann spinnt übrigends auch folgendes Thema:
https://github.com/ioBroker/ioBroker.vis-2-widgets-material/issues/114#issue-1632524052

![grafik](https://user-images.githubusercontent.com/36326543/226414935-fe6ef431-ccd1-486f-b2b6-d9b450fa9025.png)

**Comment by Feuer-sturm** [comment]
@Gurke258 Mit dem Energie Adapter Widget Version 0.1.11 ist das Problem gelöst. Siehe auch https://github.com/ioBroker/ioBroker.vis/issues/680
